### ISSUE TITLE
Cannot build with RN v0.80.2

### ISSUE THREAD

**Issue by dragorwyin** [microblink/blinkid-react-native#238]
Hello,
When I try to build the application with the newest version of this library (v7.5.0) there is following error:
`@microblink/blinkid-react-native/android/src/main/java/com/microblink/blinkid/reactnative/BlinkidReactNativeModule.kt:39:7 'onActivityResult' overrides nothing. Potential signatures for overriding:
fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent): Unit
fun onActivityResult(activity: Activity, requestCode: Int, resultCode: Int, data: Intent?): Unit FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':microblink_blinkid-react-native:compileDebugKotlin'. > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error.`

**Comment by mparadina** [comment]
Hi @dragorwyin 

We are aware of the issue with the RN v0.8 compatibility, and are working on fixing it with the next release of the SDK.
The new version of the SDK should be released by next week.

If you need any additional assistance in the meantime, please let us know.
